# Generated by Django 5.2 on 2025-06-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_date', models.DateField(blank=True, null=True)),
                ('email_time', models.TimeField(blank=True, null=True)),
                ('saved_pdf_path', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
