# Generated by Django 5.2 on 2025-06-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchmails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailorder',
            name='status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('Generated', 'Generated'), ('Failed', 'Failed')], default='Ready', max_length=20),
        ),
    ]
