# Generated by Django 5.2 on 2025-06-25 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchmails', '0002_emailorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
