# Generated by Django 5.2 on 2025-06-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchmails', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/customers_pdf/'),
        ),
    ]
