# Generated by Django 5.2 on 2025-06-28 07:13

import fetchmails.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchmails', '0005_customer_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=fetchmails.models.customer_document_upload_path),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
