# Generated by Django 5.2 on 2025-08-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchmails', '0007_customeraddress_customer_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
