# Generated by Django 5.2 on 2025-08-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchmails', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
